version: '3.8'

services:

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
      - "8082:8082"   # Registro Docker (añadir esta línea)
    volumes:
      - nexus-data:/nexus-data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  nexus-data:
  prometheus-data:
  grafana-data:
