name: CI/CD Pipeline

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fastapi-app
      NEXUS_URL: ${{ secrets.NEXUS_URL }}
      NEXUS_REPO: ${{ secrets.NEXUS_REPO }}
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pytest
          pip install httpx

      - name: Run tests
        run: |
          cd app
          pytest test_app.py

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Nexus Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.NEXUS_URL }}
          username: ${{ env.NEXUS_USER }}
          password: ${{ env.NEXUS_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.NEXUS_URL }}/${{ env.NEXUS_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f Dockerfile .

      - name: Push Docker image to Nexus
        run: |
          docker push ${{ env.NEXUS_URL }}/${{ env.NEXUS_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
