name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: fastapi-app
      IMAGE_TAG: ${{ github.sha }}
      NEXUS_URL: ${{ secrets.NEXUS_URL }}
      NEXUS_REPO: ${{ secrets.NEXUS_REPO }}
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      EC2_PATH: /home/ec2-user/proyecto-devops/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .

      - name: Save Docker image as tar
        run: |
          docker save $IMAGE_NAME:$IMAGE_TAG -o fastapi-app.tar

      - name: Fix permissions for fastapi-app.tar
        run: chmod 644 fastapi-app.tar

      - name: Copy image, compose y código a EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "fastapi-app.tar,docker-compose.fastapi.yaml,app/"
          target: ${{ env.EC2_PATH }}

      - name: Deploy and test on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd $EC2_PATH
            pwd
            docker load -i fastapi-app.tar
            docker compose -f docker-compose.fastapi.yaml up -d
            sleep 10
            FASTAPI_ID=$(docker ps -qf "ancestor=fastapi-app:${{ github.sha }}")
            docker exec $FASTAPI_ID pytest app/test_app.py
            # El contenedor permanece levantado

      - name: Log in to Nexus Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.NEXUS_URL }}
          username: ${{ env.NEXUS_USER }}
          password: ${{ env.NEXUS_PASSWORD }}

      - name: Tag and push Docker image to Nexus
        run: |
          docker tag fastapi-app:${{ github.sha }} $NEXUS_URL/$NEXUS_REPO/fastapi-app:${{ github.sha }}
          docker push $NEXUS_URL/$NEXUS_REPO/fastapi-app:${{ github.sha }}
